# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('gender', models.TextField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenteeContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(max_length=20)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(max_length=254)),
                ('linkedin_url', models.CharField(max_length=100)),
                ('facebook_url', models.CharField(max_length=100)),
                ('personal_url', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Mentee')),
            ],
        ),
        migrations.CreateModel(
            name='MenteeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('major1', models.CharField(max_length=100)),
                ('major2', models.CharField(blank=True, max_length=100, null=True)),
                ('minor1', models.CharField(blank=True, max_length=100, null=True)),
                ('minor2', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(choices=[('ba', 'Bachelor of Arts'), ('bs', 'Bachelor of Sciences'), ('m', 'Masters'), ('d', 'Ph.D'), ('pd', 'MD Ph.D'), ('md', 'MD')], max_length=3)),
                ('graduation_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(max_length=20)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(max_length=254)),
                ('linkedin_url', models.CharField(max_length=100)),
                ('facebook_url', models.CharField(max_length=100)),
                ('personal_url', models.CharField(max_length=100)),
                ('street_address', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=30)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('major1', models.CharField(max_length=100)),
                ('major2', models.CharField(blank=True, max_length=100, null=True)),
                ('minor1', models.CharField(blank=True, max_length=100, null=True)),
                ('minor2', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(choices=[('ba', 'Bachelor of Arts'), ('bs', 'Bachelor of Sciences'), ('m', 'Masters'), ('d', 'Ph.D'), ('pd', 'MD Ph.D'), ('md', 'MD')], max_length=3)),
                ('graduation_year', models.DateField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorMenteePairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('comments', models.TextField()),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Mentor')),
            ],
        ),
        migrations.AddField(
            model_name='menteeeducation',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentoring.Mentor'),
        ),
    ]
