# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mentorcontactinformation',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentorcontactinformation',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mentorcontactinformation',
            name='street_address',
            field=models.CharField(max_length=100),
        ),
    ]
