# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_auto_20161016_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteecontactinformation',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menteecontactinformation',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menteecontactinformation',
            name='personal_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorcontactinformation',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorcontactinformation',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorcontactinformation',
            name='personal_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
