# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_auto_20161016_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
