# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0006_auto_20161027_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorcontactinformation',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mentorcontactinformation',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
