# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0010_mentorpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorpreference',
            name='mentee',
        ),
        migrations.AddField(
            model_name='mentorpreference',
            name='mentor',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='mentoring.Mentor'),
            preserve_default=False,
        ),
    ]
