# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0012_auto_20161027_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormenteepairs',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentormenteepairs',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
