# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0014_auto_20161203_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteepreference',
            name='first_choice',
            field=models.CharField(choices=[('1', 'Choice of Major'), ('2', 'Academia or Industry'), ('3', 'Resume/CV Critique'), ('4', 'Parenting vs Career'), ('5', 'Work life balance'), ('6', 'Life after Iowa'), ('7', 'Study Abroad'), ('8', 'International Experience'), ('9', 'Fellowships'), ('10', 'Goals'), ('11', 'Shadowing Opportunities'), ('12', 'Grad school applications'), ('13', 'Med school applications'), ('14', 'Job/Internship search'), ('15', 'Networking'), ('16', 'Advanced degrees'), ('17', 'Workplace issues'), ('18', 'Personal Experiences'), ('19', 'Gender specific')], max_length=2),
        ),
        migrations.AlterField(
            model_name='menteepreference',
            name='second_choice',
            field=models.CharField(blank=True, choices=[('1', 'Choice of Major'), ('2', 'Academia or Industry'), ('3', 'Resume/CV Critique'), ('4', 'Parenting vs Career'), ('5', 'Work life balance'), ('6', 'Life after Iowa'), ('7', 'Study Abroad'), ('8', 'International Experience'), ('9', 'Fellowships'), ('10', 'Goals'), ('11', 'Shadowing Opportunities'), ('12', 'Grad school applications'), ('13', 'Med school applications'), ('14', 'Job/Internship search'), ('15', 'Networking'), ('16', 'Advanced degrees'), ('17', 'Workplace issues'), ('18', 'Personal Experiences'), ('19', 'Gender specific')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='menteepreference',
            name='third_choice',
            field=models.CharField(blank=True, choices=[('1', 'Choice of Major'), ('2', 'Academia or Industry'), ('3', 'Resume/CV Critique'), ('4', 'Parenting vs Career'), ('5', 'Work life balance'), ('6', 'Life after Iowa'), ('7', 'Study Abroad'), ('8', 'International Experience'), ('9', 'Fellowships'), ('10', 'Goals'), ('11', 'Shadowing Opportunities'), ('12', 'Grad school applications'), ('13', 'Med school applications'), ('14', 'Job/Internship search'), ('15', 'Networking'), ('16', 'Advanced degrees'), ('17', 'Workplace issues'), ('18', 'Personal Experiences'), ('19', 'Gender specific')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mentorpreference',
            name='first_choice',
            field=models.CharField(choices=[('1', 'Choice of Major'), ('2', 'Academia or Industry'), ('3', 'Resume/CV Critique'), ('4', 'Parenting vs Career'), ('5', 'Work life balance'), ('6', 'Life after Iowa'), ('7', 'Study Abroad'), ('8', 'International Experience'), ('9', 'Fellowships'), ('10', 'Goals'), ('11', 'Shadowing Opportunities'), ('12', 'Grad school applications'), ('13', 'Med school applications'), ('14', 'Job/Internship search'), ('15', 'Networking'), ('16', 'Advanced degrees'), ('17', 'Workplace issues'), ('18', 'Personal Experiences'), ('19', 'Gender specific')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mentorpreference',
            name='second_choice',
            field=models.CharField(blank=True, choices=[('1', 'Choice of Major'), ('2', 'Academia or Industry'), ('3', 'Resume/CV Critique'), ('4', 'Parenting vs Career'), ('5', 'Work life balance'), ('6', 'Life after Iowa'), ('7', 'Study Abroad'), ('8', 'International Experience'), ('9', 'Fellowships'), ('10', 'Goals'), ('11', 'Shadowing Opportunities'), ('12', 'Grad school applications'), ('13', 'Med school applications'), ('14', 'Job/Internship search'), ('15', 'Networking'), ('16', 'Advanced degrees'), ('17', 'Workplace issues'), ('18', 'Personal Experiences'), ('19', 'Gender specific')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mentorpreference',
            name='third_choice',
            field=models.CharField(blank=True, choices=[('1', 'Choice of Major'), ('2', 'Academia or Industry'), ('3', 'Resume/CV Critique'), ('4', 'Parenting vs Career'), ('5', 'Work life balance'), ('6', 'Life after Iowa'), ('7', 'Study Abroad'), ('8', 'International Experience'), ('9', 'Fellowships'), ('10', 'Goals'), ('11', 'Shadowing Opportunities'), ('12', 'Grad school applications'), ('13', 'Med school applications'), ('14', 'Job/Internship search'), ('15', 'Networking'), ('16', 'Advanced degrees'), ('17', 'Workplace issues'), ('18', 'Personal Experiences'), ('19', 'Gender specific')], max_length=2, null=True),
        ),
    ]
