# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0015_auto_20161203_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteecontactinformation',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
