# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0016_auto_20161204_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='confirmation_token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='confirmation_token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
