# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0017_auto_20161214_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='active_until',
            field=models.DateTimeField(default=datetime.datetime.utcnow() + datetime.timedelta(days=1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='active_until',
            field=models.DateTimeField(default=datetime.datetime.utcnow() + datetime.timedelta(days=1)),
            preserve_default=False,
        ),
    ]
