# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0018_auto_20161214_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
