# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0019_auto_20161214_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoreducation',
            name='degree',
            field=models.CharField(blank=True, choices=[('ba', 'Bachelor of Arts'), ('bs', 'Bachelor of Sciences'), ('m', 'Masters'), ('d', 'Ph.D'), ('pd', 'MD Ph.D'), ('md', 'MD')], max_length=3, null=True),
        ),
    ]
