# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0020_auto_20161215_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoreducation',
            name='degree',
            field=models.CharField(choices=[('ba', 'Bachelor of Arts'), ('bs', 'Bachelor of Sciences'), ('m', 'Masters'), ('d', 'Ph.D'), ('pd', 'MD Ph.D'), ('md', 'MD')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentoreducation',
            name='graduation_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
