# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0022_auto_20170108_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='other',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='went_poorly',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='went_well',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
