# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0023_auto_20170108_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='active',
        ),
    ]
