# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-24 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0025_auto_20171212_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='new_gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
