# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-24 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0026_mentor_new_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='new_gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
