# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-24 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0028_swap_over_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='gender',
        ),
    ]
